### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by csdodd** [bakkenbaeck/PorchPirateProtector#1]
Add a quick overview on how to get this compiling for Android and iOS.

A high-level view of architecture could also be useful since this is a K/N project.

**Comment by designatednerd** [comment]
🤦‍♀️Was totally planning on this and then squirreled out on it. Will do today!

**Comment by designatednerd** [comment]
Addressed via [f42f1a3](https://github.com/bakkenbaeck/PorchPirateProtector/commit/f42f1a30f57e23453bcf904f865f5243135a7dd0) - please let me know if this works for you or if there are other pieces of info you're looking for.

**Comment by csdodd** [comment]
Yep, nice work.
